### PR TITLE
Applied patch https://issues.apache.org/jira/browse/HIVE-2332

### PR DESCRIPTION
**Pull request by jhartlaub**
Fix ArrayOutOfBoundsException in hive caused by the case where expressions in the GROUP BY appear in the DISTINCT clause.

### CODE REVIEW

**Comment by jhartlaub** [comment]
@mbautin - applied the patch.

**Comment by mbautin** [comment]
@vnivargi @jhartlaub the test added by this patch fails: http://jenkins.clearstorydatainc.com/job/hive_TestCliDriver/19/

**Comment by jhartlaub** [comment]
odd, I ran it manually and it appeared to work.

**Comment by jhartlaub** [comment]
fwiw, the actual queries are executing and correct when deployed (in my
vm), I think this might be a case where the test is failing due to
something related to the test.  I'm looking at it.

-Jon

**Comment by mbautin** [comment]
It looks like https://github.com/clearstorydata/hive/pull/15 is needed to make it work, because the expected test output contains paths with author's username.

**Pull request merged**
